mysite/urls.py
from django.contrib import admin
from django.urls import include, path
from django.views.generic import RedirectView
from polls import views

urlpatterns = [
    path("admin/", admin.site.urls),
    path("polls/", include("polls.urls")),
    path("accounts/logout/", views.logout_view, name="logout"),
    path("accounts/", include('django.contrib.auth.urls')),
    path("signup/", views.signup, name="signup"),
    path("", RedirectView.as_view(url="/polls/")),
]

polls/urls.py
"""Urls path for /polls/."""
from django.urls import path
from . import views

app_name = 'polls'
urlpatterns = [
    # /polls/
    path("", views.IndexView.as_view(), name="index"),
    # /polls/number/detail/
    path("<int:pk>/", views.DetailView.as_view(), name="detail"),
    # /polls/number/results/
    path("<int:pk>/results/", views.ResultsView.as_view(), name="results"),
    # /polls/number/vote/
    path("<int:question_id>/vote/", views.vote, name="vote"),
    # /polls/number/reset/
    path("<int:question_id>/reset/", views.reset_vote, name="reset"),
]

polls/models.py
"""Models for django MVT structure."""
import datetime
from django.contrib import admin
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User


class Question(models.Model):
    """
    Question model for polls with two attributes.

    1. question_text as the question.
    2. pub_date as the publishing date.
    """

    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published', default=timezone.now)
    end_date = models.DateTimeField('ended date', blank=True, null=True)

    @admin.display(
        boolean=True,
        ordering="pub_date",
        description="Published recently?",
    )
    def was_published_recently(self):
        """Check whether this question is publicly active."""
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.pub_date <= now

    @admin.display(
        boolean=True,
        ordering="pub_date",
        description="Published?",
    )
    def is_published(self):
        """Return checking whether this question has been published or not."""
        now = timezone.now()
        return now >= self.pub_date

    def can_vote(self):
        """
        Return boolean for checking whether the question is in voting time.

        Checking whether this question is between the voting time.
        """
        now = timezone.now()
        if self.end_date is None:
            return self.pub_date <= now
        return self.pub_date <= now <= self.end_date

    def __str__(self):
        """Display question text when print out the object."""
        return self.question_text


class Choice(models.Model):
    """
    Choice model for polls with three attributes.

    1. Question to define which choice it belongs to.
    2. Choice_text as the choice.
    3. Votes to keep track of the votes this choice has.
    """

    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)

    @property
    def votes(self):
        """Return number of votes this choice has."""
        return self.vote_set.count()

    def __str__(self):
        """Display the text of the choice when print out the object."""
        return self.choice_text


class Vote(models.Model):
    """Vote model for user to vote for a choice in a poll."""

    choice = models.ForeignKey(Choice, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        """Return text of the user and their choice."""
        return f"{self.user.username} voted for {self.choice.choice_text}"

polls/views.py
"""Views for django MVT models."""
from django.http import HttpResponseRedirect
from django.shortcuts import render, get_object_or_404, Http404, redirect
from django.urls import reverse
from django.views import generic
from django.utils import timezone

from django.contrib import messages
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import logout, login, authenticate
from django.contrib.auth.decorators import login_required

from polls.models import Question, Choice, Vote

from django.dispatch import receiver
from django.contrib.auth.signals import user_logged_in, user_login_failed
import logging

logger = logging.getLogger(__name__)


class IndexView(generic.ListView):
    """Displays the home page of the site with all the polls."""

    template_name = "polls/index.html"
    context_object_name = "latest_question_list"

    def get_queryset(self):
        """Return all published questions queryset."""
        return Question.objects.filter(pub_date__lte=timezone.now()
                                       ).order_by("-pub_date")


class DetailView(generic.DetailView):
    """Display the choices for a poll and allow voting."""

    model = Question
    template_name = "polls/detail.html"

    def get_queryset(self):
        """Excludes any questions that aren't published yet."""
        return Question.objects.filter(pub_date__lte=timezone.now())

    def get_context_data(self, *args, **kwargs):
        """
        Return the context data for the view.

        If user vote then show the vote to user in a message and radio checked.
        """
        context = super().get_context_data(**kwargs)
        current_user = self.request.user
        question = self.get_object()
        context["question"] = question
        if current_user.is_authenticated:
            try:
                user_vote = Vote.objects.get(user=current_user,
                                             choice__question=question.id)
                messages.add_message(self.request, messages.INFO,
                                     f"Previously {user_vote}")
            except (KeyError, Vote.DoesNotExist):
                user_vote = None
            context["user_vote"] = user_vote
            return context
        else:
            context["user_vote"] = None
            return context

    def dispatch(self, request, *args, **kwargs):
        """
        Return dispatch result if the website exists or not.

        Try to get a question object, except error 404.
        Then it will redirect to index page with response 302.
        """
        try:
            q_object = self.get_object()
            if not q_object.is_published():
                messages.error(request, "This question is not yet published.")
                return redirect(reverse('polls:index'))
            elif not q_object.can_vote():
                messages.error(request, "Voting is not allowed "
                                        "for this question.")
                return redirect(reverse('polls:index'))
            else:
                return super().dispatch(request, *args, **kwargs)
        except Http404:
            # Temporary redirect to another page if the object is not found
            messages.error(request, f"Question {kwargs['pk']} does not exist.")
            return redirect(reverse('polls:index'))


class ResultsView(generic.DetailView):
    """Display a result page for user to see current votes."""

    def dispatch(self, request, *args, **kwargs):
        """
        Return dispatch result if the website exists or not.

        Try to get a question object, except error 404.
        Then it will redirect to index page with response 302.
        """
        try:
            q_object = self.get_object()
            if not q_object.is_published():
                messages.error(request, "This question is not yet published.")
                return redirect(reverse('polls:index'))
            else:
                return super().dispatch(request, *args, **kwargs)
        except Http404:
            # Temporary redirect to another page if the object is not found
            messages.error(request, f"Question {kwargs['pk']} does not exist.")
            return redirect(reverse('polls:index'))

    model = Question
    template_name = "polls/results.html"


@login_required
def vote(request, question_id):
    """
    Return the vote for a particular question.

    Check for published question and redirect to result page after voting.
    """
    question = get_object_or_404(Question, pk=question_id)

    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        messages.error(request, "Please select a choice")
        return render(request,
                      'polls/detail.html',
                      {
                          "question": question,
                      },
                      )
    # User variable
    current_user = request.user
    # Get the user's vote
    try:
        # user has a vote for this question
        user_vote = Vote.objects.get(user=current_user,
                                     choice__question=question)
        user_vote.choice = selected_choice
        messages.success(request,
                         f"Your vote has updated to "
                         f"{selected_choice.choice_text}")
        user_vote.save()
    except Vote.DoesNotExist:
        # user doesn't have a vote for this question
        Vote.objects.create(user=current_user, choice=selected_choice)
        messages.success(request,
                         f"You have voted for {selected_choice.choice_text}")
    logger.info(f"{current_user.username} votes for "
                f"{selected_choice.choice_text} at question {question.id}")
    return HttpResponseRedirect(
        reverse("polls:results", args=(question.id,)))


@login_required
def reset_vote(request, question_id):
    """
    Reset user's vote for a particular question.

    Check for published question
    and redirect to result page after reset voting.
    """
    question = get_object_or_404(Question, pk=question_id)

    # User variable
    current_user = request.user
    # Get the user's vote
    try:
        # user has a vote for this question
        user_vote = Vote.objects.get(user=current_user,
                                     choice__question=question)
        user_vote.delete()
        messages.success(request, "You have reset your vote")
    except Vote.DoesNotExist:
        # user doesn't have a vote for this question
        messages.success(request, "No vote reset required")
    logger.info(f"{current_user.username} reset votes "
                f"for question {question.id}")
    return HttpResponseRedirect(
        reverse("polls:results", args=(question.id,)))


def signup(request):
    """Register a new user."""
    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            # get named fields from the form data and password input field
            # called 'password1'
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=password)
            login(request, user)
            return redirect("polls:index")
        else:
            messages.error(request, "Not valid form.")
            return render(request, 'registration/signup.html', {'form': form})
    else:
        # Create a form and display
        form = UserCreationForm()
    return render(request, 'registration/signup.html', {'form': form})


def get_client_ip(request):
    """Get the visitor’s IP address using request headers."""
    x_forwarded_for = request.META.get('HTTP_X_FORWARDED_FOR')
    if x_forwarded_for:
        ip = x_forwarded_for.split(',')[0]
    else:
        ip = request.META.get('REMOTE_ADDR')
    return ip


@login_required
def logout_view(request, *args, **kwargs):
    """Return a shortcut to redirect user to login page after logout."""
    ip_address = get_client_ip(request)
    logout(request)
    logger.info(f"Logged out from {ip_address}")
    return redirect("login")


@receiver(user_logged_in)
def user_logged_in_callback(sender, request, user, **kwargs):
    """Show logs for the user login success."""
    ip_address = get_client_ip(request)
    logger.info(f'Login user: {user} via ip: {ip_address}')


@receiver(user_login_failed)
def user_login_failed_callback(sender, credentials, request, **kwargs):
    """Show logs the user login failed."""
    ip_address = get_client_ip(request)
    logger.warning(f'login failed: {ip_address}')

polls/templates/polls/detail.html
<html>
<head>
    {% load static %}
    <link rel="stylesheet" href="{% static 'polls/style.css' %}">
</head>
<body>
<div class="q_vote">
    <fieldset>
        <legend><h1>{{ question.question_text }}</h1></legend>

        <!--Handle an error message-->
        {% if messages %}
        <div class="display_message">
            <p class="messages">
                {% for msg in messages %}
            <p class="{{msg.tags}}" style="color: red; text-align: center">
                <strong>{{ msg }}</strong>
            </p>
            {% endfor %}
            </p>
        </div>
        {% endif %}

        <form action="{% url 'polls:vote' question.id %}" method="post"
              style="display: inline-block">
            {% csrf_token %}
            <!--Radio buttons-->
            {% for choice in question.choice_set.all %}
            <input type="radio" name="choice" id="choice{{ forloop.counter }}"
                   value="{{ choice.id }}"
                   {% if user_vote and user_vote.choice.id == choice.id %} checked {% endif %}>
            <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br>
            {% endfor %}
    </fieldset>

    <!--Vote Button-->
    <input type="submit" value="Vote" class="button">
    </form>
    <form action="{% url 'polls:reset' question.id %}" method="post"
          style="display: inline-block">
        {% csrf_token %}
        <input type="submit" value="Remove Vote" class="button">
    </form>
    <a href="{% url 'polls:results' question.id %}" class="button_text">
        <button type="button" class="button">
            Results
        </button>
    </a>
    <a href="{% url 'polls:index' %}" class="button_text">
        <button type="button" class="button">
            Go back to voting list
        </button>
    </a>
</div>
</body>
</html>

polls/templates/polls/index.html
<html>
<head>
    {% load static %}
    <link rel="stylesheet" href="{% static 'polls/style.css' %}">
    {% if latest_question_list %}
    <h1>
        <span style="text-align: right; text-anchor: end">
        Polls
        </span>
        <span style="text-align: left">
        <!--Check for user login-->
        {% if user.is_authenticated %}
            <form action="{% url 'logout' %}" method="post"
                  style="display: inline">
                {% csrf_token %}
                <button type="submit" class="button">Log Out</button>
            </form>
            Welcome back, {{ user.username }}
        {% else %}
            Please <a href="{% url 'login' %}?next={{request.path}}"
                      style="text-decoration: none;
                      color: green;">Login</a>
        {% endif %}
        </span>
    </h1>
    <!--Handle an error message-->
    {% if messages %}
        <div class="display_message">
            <p class="messages">
                {% for msg in messages %}
                <p class="{{msg.tags}}" style="color: red; text-align: center">
                    <strong>{{ msg }}</strong>
                </p>
                {% endfor %}
            </p>
        </div>
    {% endif %}
    {% else %}
        <p>No polls are available.</p>
    {% endif %}
</head>
<body>
    <div class="center" style="background: none">
        <!--Show valid question boxes-->
        {% for question in latest_question_list %}
            <div class="question_box">
                <!--Called value of url name detail in polls/urls.py-->
                {% if question.can_vote %}
                    <a href="{% url 'polls:detail' question.id %}"
                       class="question_text"
                       style="color: green">{{ question.question_text }}</a>
                {% elif question.is_published %}
                    <a href="{% url 'polls:results' question.id %}"
                       class="question_text"
                       style="color: red">{{ question.question_text }}</a>
                {% endif %}
                    <a href="{% url 'polls:results' question.id %}"
                       class="button_text">
                        <button class="button">
                            Results
                        </button>
                    </a>
            </div>
        {% endfor %}
    </div>
</body>
</html>

polls/templates/polls/results.html
<html>
<head>
    {% load static %}
    <link rel="stylesheet" href="{% static 'polls/style.css' %}">
</head>
<body>
<h1>{{ question.question_text }}</h1>
<div class="center" style="max-width: 20%; font-size: large;">

    <table class="results" style="width: 100%; table-layout: fixed;">
        <tr>
            <th style="text-align: left; padding-right: 10px; width: 70%;">
                Options
            </th>
            <th style="text-align: right; padding-left: 10px; width: 30%;">
                Votes
            </th>
        </tr>
        {% for choice in question.choice_set.all %}
        <tr>
            <td style="text-align: left; padding-right: 10px;">{{ choice.choice_text }}
            </td>
            <td style="text-align: right; padding-left: 10px;">{{ choice.votes }}
            </td>
        </tr>
        {% endfor %}
    </table>
</div>
<!--message-->
{% if messages %}
<div class="display_message">
    <p class="messages">
        {% for msg in messages %}
        <p class="{{msg.tags}}" style="color: green; text-align: center">
            <strong>{{ msg }}</strong>
        </p>
        {% endfor %}
    </p>
</div>
{% endif %}
<a href="{% url 'polls:index' %}" class="button_text">
    <button type="button" class="button">
        Home
    </button>
</a>
</body>
</html>